### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Yezzipe** [tacodrake95/GalaxyPopulator#1]
Got this error : 

Traceback (most recent call last):
  File "D:\FTBSkyOdyssey\minecraft\saves\New World\advRocketry\galaxyPopulator.py", line 142, in <module>
    block = genStarSystem(block, name, planetNames)
  File "D:\FTBSkyOdyssey\minecraft\saves\New World\advRocketry\galaxyPopulator.py", line 110, in genStarSystem
    size = truncate(random.uniform(minStarSize, maxStarSize), 1)
  File "D:\FTBSkyOdyssey\minecraft\saves\New World\advRocketry\galaxyPopulator.py", line 24, in truncate
    s = '{}'.format(f)
ValueError: zero length field name in format

**Comment by AQuAWoman** [comment]
What version of python are you running? This will not work on python < 2.7 and is recommended 3.6 or above

**Comment by AQuAWoman** [comment]
I think I can write a more narrow truncation function just for going down to a single decimal place which should work on older versions of python too. Let me see if that works really quick.

**Comment by AQuAWoman** [comment]
This ought to be fixed in the latest push, try and give that a go.
